from collections import defaultdict

policy_sectors = [
    "Energy",
    "LULUCF",
    "Buildings",
    "Economy-wide",
    "Water",
    "Urban",
    "Transport",
    "Public Sector",
    "Health",
    "Environment",
    "Agriculture",
    "Industry",
    "Tourism",
    "Waste",
    "Coastal zones",
    "Cross Cutting Area",
    "Disaster Risk Management (Drm)",
    "Finance",
    "Rural",
    "Social development",
    "Adaptation",
    "Residential and Commercial",
]

countries = [
    "South Korea",
    "Papua New Guinea",
    "Japan",
    "Czechia",
    "Guyana",
    "China",
    "United States of America",
    "Estonia",
    "Zambia",
    "Armenia",
    "Albania",
    "Ireland",
    "Niue",
    "Zimbabwe",
    "Sierra Leone",
    "Tonga",
    "Singapore",
    "Turkey",
    "Nigeria",
    "Chad",
    "Norway",
    "Liberia",
    "Croatia",
    "Yemen",
    "Timor-Leste",
    "Iceland",
    "Haiti",
    "Fiji",
    "Botswana",
    "Seychelles",
    "Maldives",
    "Ghana",
    "European Union",
    "Marshall Islands",
    "Afghanistan",
    "Kenya",
    "Mauritius",
    "Denmark",
    "Azerbaijan",
    "Taiwan",
    "Cook Islands",
    "New Zealand",
    "Malaysia",
    "Slovenia",
    "Tanzania",
    "Vanuatu",
    "Finland",
    "United Kingdom",
    "India",
    "Kyrgyzstan",
    "Spain",
    "Netherlands",
    "Luxembourg",
    "Guinea",
    "Egypt",
    "Philippines",
    "Georgia",
    "Lao People's Democratic Republic",
    "Lithuania",
    "Bhutan",
    "Canada",
    "Hungary",
    "Uganda",
    "Indonesia",
    "Vietnam",
    "Bangladesh",
    "Uzbekistan",
    "Slovakia",
    "Belize",
    "Rwanda",
    "Kiribati",
    "South Africa",
    "Namibia",
    "Malta",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Micronesia",
    "Oman",
    "Bahrain",
    "Lebanon",
    "San Marino",
    "Ethiopia",
    "Suriname",
    "Malawi",
    "North Macedonia (Republic of North Macedonia)",
    "Antigua and Barbuda",
    "Bahamas, The",
    "Barbados",
    "Dominica",
    "Thailand",
    "Myanmar",
    "Australia",
    "Tajikistan",
    "Samoa",
    "Lesotho",
    "Gambia",
    "Cambodia",
    "Pakistan",
    "Saudi Arabia",
    "United Arab Emirates",
    "Serbia",
    "Sri Lanka",
    "Solomon Islands",
    "Palau",
    "Nauru",
    "Eswatini",
    "Qatar",
    "Poland",
    "Palestine",
    "Israel",
    "Tuvalu",
    "Belgium",
    "Italy",
    "Austria",
    "Germany",
    "Bulgaria",
    "Cyprus",
    "Kuwait",
    "France",
    "Greece",
    "Somalia",
    "Latvia",
    "Jordan",
    "Portugal",
    "Romania",
    "Moldova",
    "Switzerland",
    "Côte d'Ivoire",
    "Brunei Darussalam",
    "Ukraine",
    "Algeria",
    "Dominican Republic",
    "Belarus",
    "Argentina",
    "Russia",
    "Grenada",
    "Cuba",
    "Venezuela",
    "Nepal",
    "South Sudan",
    "Bolivia",
    "Ecuador",
    "Montenegro",
    "Sweden",
    "Trinidad and Tobago",
    "Libya",
    "Brazil",
    "No Geography",
    "Mali",
    "Tunisia",
    "Sudan",
    "Mongolia",
    "Burundi",
    "Peru",
    "Mozambique",
    "Costa Rica",
    "Turkmenistan",
    "Niger",
    "Sao Tome and Principe",
    "International",
    "Burkina Faso",
    "Jamaica",
    "Cameroon",
    "Kazakhstan",
    "Mexico",
    "Colombia",
    "Morocco",
    "Togo",
    "Uruguay",
    "Chile",
    "Eritrea",
    "Gabon",
    "Cabo Verde",
    "Liechtenstein",
    "Bosnia and Herzegovina",
    "Kosovo",
    "Angola",
    "Benin",
    "Korea, North",
    "Djibouti",
    "Hong Kong",
    "Guinea-Bissau",
    "Iran",
    "Monaco",
    "Syria",
    "Central African Republic",
    "Madagascar",
    "Andorra",
    "Equatorial Guinea",
]

sector_mapping = {
    "Freedom in the World": [
        "Public Sector",
        "Cross Cutting Area",
        "Social development",
    ],
    "V-Dem Country-Year (Full + Others)": [
        "Public Sector",
        "Cross Cutting Area",
        "Social development",
    ],
    "AI Index Report": ["Industry", "Economy-wide", "Cross Cutting Area"],
    "Life Expectancy at birth": ["Health", "Social development"],
    "How Was Life? Global Well-being since 1820 and World Bank": [
        "Health",
        "Social development",
        "Economy-wide",
    ],
    "EIU Democratic Index (2006-2023)": [
        "Public Sector",
        "Cross Cutting Area",
        "Social development",
    ],
    "Population": ["Economy-wide", "Urban", "Rural", "Health", "Social development"],
    "Latent Estimates of Historic Population": [
        "Economy-wide",
        "Urban",
        "Rural",
        "Health",
        "Social development",
    ],
    "Democratic Mood": ["Public Sector", "Cross Cutting Area", "Social development"],
    "Living Planet Index – WWF (2022)": [
        "Environment",
        "Agriculture",
        "LULUCF",
        "Water",
    ],
    "Global Human Settlement Layer Dataset": [
        "Urban",
        "Buildings",
        "Residential and Commercial",
        "Environment",
    ],
    "Boix-Miller-Rosato (BMR) dichotomous coding of democracy (1800-2020)": [
        "Public Sector",
        "Cross Cutting Area",
        "Social development",
    ],
    "Bertelsmann Transformation Index, Scores": [
        "Public Sector",
        "Economy-wide",
        "Industry",
        "Cross Cutting Area",
        "Social development",
    ],
    "Global Wellbeing Initiative (Gallup, 2020)": ["Health", "Social development"],
    "World Population Prospects": [
        "Economy-wide",
        "Urban",
        "Rural",
        "Health",
        "Social development",
    ],
    "Inputs: Land Use": ["LULUCF", "Agriculture", "Environment"],
    "Population size by education level (Wittgenstein Centre, 2018)": [
        "Social development",
        "Public Sector",
        "Economy-wide",
    ],
    "Polity5 Project, Political Regime Characteristics and Transitions, 1800-2018": [
        "Public Sector",
        "Cross Cutting Area",
        "Social development",
    ],
    "Episodes of Regime Transformation": [
        "Public Sector",
        "Cross Cutting Area",
        "Social development",
    ],
    "Wittgenstein Center Population and Human Capital Projections": [
        "Economy-wide",
        "Social development",
        "Health",
    ],
    "Democratic Satisfaction": [
        "Public Sector",
        "Cross Cutting Area",
        "Social development",
    ],
    "145 key tourism statistics": ["Tourism"],
    "Historical numeracy and years of schooling estimates (Clio Infra)": [
        "Social development",
        "Economy-wide",
        "Public Sector",
    ],
    "Lexical Index of Electoral Democracy (LIED)": [
        "Public Sector",
        "Cross Cutting Area",
        "Social development",
    ],
    "Human Capital in the Long Run": ["Economy-wide", "Social development", "Health"],
    "Population density (various sources, 2023.2)": [
        "Urban",
        "Rural",
        "Environment",
        "Health",
    ],
    "Historical World Population Prospects": [
        "Economy-wide",
        "Urban",
        "Rural",
        "Health",
        "Social development",
    ],
    "World Development Indicators": [
        "Economy-wide",
        "Health",
        "Environment",
        "Agriculture",
        "Water",
        "Energy",
        "Transport",
        "Industry",
    ],
    "Public Expenditure on Education OECD": [
        "Public Sector",
        "Social development",
        "Economy-wide",
    ],
    "World Happiness Report": ["Health", "Social development", "Economy-wide"],
    "Tourism direct GDP as a proportion of total GDP": ["Tourism", "Economy-wide"],
    "Cross-country literacy rates": [
        "Social development",
        "Public Sector",
        "Economy-wide",
    ],
    "AI Policy (AI Index, 2023)": ["Public Sector", "Cross Cutting Area", "Industry"],
    "Implementation of standards accounting tools to monitor the economic and environmental aspects of tourism sustainability": [
        "Tourism",
        "Environment",
        "Economy-wide",
    ],
    "Global Primary Energy": ["Energy", "Economy-wide"],
    "Mandatory preventive measures (new buildings)": [
        "Buildings",
        "Energy",
        "Residential and Commercial",
    ],
    "NLIS: Population using improved drinking-water sources (%)": [
        "Water",
        "Health",
        "Social development",
    ],
    "Maddison Project Database": ["Economy-wide", "Industry", "Agriculture"],
    "Fossil fuel reserves/production ratio": ["Energy", "Environment"],
    "Share of agriculture in GDP at current prices (Herrendorf et al. and GGDC-10 data) (split)": [
        "Agriculture",
        "Economy-wide",
    ],
    "Daily calorie supply per person": ["Agriculture", "Health", "Social development"],
    "Radon in building regulations for new buildings": [
        "Buildings",
        "Health",
        "Residential and Commercial",
        "Public Sector",
    ],
    "Amount of water- and sanitation-related official development assistance that is part of a government-coordinated spending plan (current US$ millions)": [
        "Water",
        "Public Sector",
        "Finance",
        "Health",
    ],
    "European Bathing Water Quality": ["Water", "Health", "Environment", "Tourism"],
    "SDG 6.3.1 Proportion of safely treated domestic wastewater flows (%)": [
        "Water",
        "Waste",
        "Environment",
        "Health",
    ],
    "Fossil fuel production": ["Energy", "Industry", "Economy-wide"],
    "Existence of national reference level for buildings with high public occupancy": [
        "Buildings",
        "Public Sector",
        "Health",
        "Residential and Commercial",
    ],
    "Water, sanitation and hygiene attributable DALYs ('000)": [
        "Water",
        "Health",
        "Environment",
    ],
    "Smoke-free public transport (national legislation)": [
        "Transport",
        "Public Sector",
        "Health",
    ],
    "Population using at least basic drinking-water services (%)": [
        "Water",
        "Health",
        "Social development",
    ],
    "Attainable yields": ["Agriculture", "Environment"],
    "Mandatory mitigation measures if legal value is exceeded (existing buildings)": [
        "Buildings",
        "Public Sector",
        "Health",
        "Residential and Commercial",
    ],
    "Existence of dementia-friendly initiative to improve accessibility of public transportation": [
        "Transport",
        "Public Sector",
        "Health",
        "Social development",
    ],
    "Compliance with smoke-free public transport law (score)": [
        "Transport",
        "Public Sector",
        "Health",
    ],
    "Long-term wheat yields": ["Agriculture", "Environment", "Economy-wide"],
    "Radon in building regulations for existing buildings i.e. renovation/remodeling/major alteration": [
        "Buildings",
        "Health",
        "Residential and Commercial",
        "Public Sector",
    ],
    "Vehicle standards": ["Transport", "Public Sector", "Environment", "Industry"],
    "Population using safely managed drinking-water services (%)": [
        "Water",
        "Health",
        "Social development",
    ],
    "Number of registered vehicles": ["Transport", "Economy-wide", "Urban"],
    "Water, sanitation and hygiene attributable deaths per 100'000 capita": [
        "Water",
        "Health",
        "Environment",
    ],
    "Primary energy consumption": ["Energy", "Economy-wide", "Environment"],
    "Water, sanitation and hygiene attributable DALYs per 100'000 capita": [
        "Water",
        "Health",
        "Environment",
    ],
    "Radon concentration measurements for existing buildings": [
        "Buildings",
        "Health",
        "Residential and Commercial",
    ],
    "Reference level for buildings with high public occupancy (Bq/m3)": [
        "Buildings",
        "Public Sector",
        "Health",
        "Residential and Commercial",
    ],
    "Solar photovoltaic cost and capacity": ["Energy", "Industry", "Economy-wide"],
    "Radon in national drinking-water regulations": [
        "Water",
        "Health",
        "Public Sector",
    ],
    "Energy mix": ["Energy", "Economy-wide", "Environment"],
    "Registered vehicles per 1,000 people": ["Transport", "Economy-wide", "Urban"],
    "Comtrade Database": [
        "Economy-wide",
        "Industry",
        "Agriculture",
        "Energy",
        "Transport",
    ],
    "Long-term crop yields": ["Agriculture", "Environment", "Economy-wide"],
    "Air transport CO2 emissions (experimental)": [
        "Transport",
        "Environment",
        "Energy",
    ],
    "Electricity mix": ["Energy", "Economy-wide", "Environment"],
    "Global Plastics Outlook - Plastics waste in 2019 by region, polymer and application": [
        "Waste",
        "Industry",
        "Environment",
    ],
    "Best-practice policy implemented for industrially produced trans-fatty acids (TFA) (Y/N)": [
        "Health",
        "Industry",
        "Public Sector",
    ],
    "Ocean Heat Content": ["Environment", "Water", "Coastal zones"],
    "Radon concentration measurements for new buildings": [
        "Buildings",
        "Health",
        "Residential and Commercial",
    ],
    "Global Monthly Emissions from Wildfires": [
        "Environment",
        "LULUCF",
        "Disaster Risk Management (Drm)",
    ],
    "Total density per million population: Positron Emission tomography": [
        "Health",
        "Public Sector",
    ],
    "National health and climate change plan or strategy developed": [
        "Health",
        "Public Sector",
        "Environment",
        "Cross Cutting Area",
    ],
    "Agreement in place between the Ministry of Health and other sector(s) in relation to health and climate change policy or programs": [
        "Health",
        "Public Sector",
        "Environment",
        "Cross Cutting Area",
    ],
    "Intact Forest Landscapes": ["Environment", "LULUCF", "Agriculture"],
    "Designation of a focal point responsible for health and climate change within the Ministry of Health": [
        "Health",
        "Public Sector",
        "Environment",
        "Cross Cutting Area",
    ],
    "Monthly greenhouse gas concentration": ["Environment", "Energy", "Economy-wide"],
    "Climate change attributable DALYs per 100'000 capita": [
        "Health",
        "Environment",
        "Cross Cutting Area",
    ],
    "Global Plastics Outlook - Greenhouse gas emissions from primary plastics": [
        "Waste",
        "Industry",
        "Environment",
        "Energy",
    ],
    "United Nations Sustainable Development Goals (2023-Q2)": [
        "Cross Cutting Area",
        "Economy-wide",
        "Health",
        "Environment",
        "Agriculture",
        "Energy",
        "Water",
        "Industry",
        "Transport",
        "Social development",
    ],
    "Fluorinated gas emissions by sector": ["Environment", "Industry", "Energy"],
    "Climate change attributable deaths": [
        "Health",
        "Environment",
        "Cross Cutting Area",
    ],
    "Methane emissions by sector": ["Energy", "Agriculture", "Waste", "Environment"],
    "Existence of a multi-stakeholder mechanism on health and climate change": [
        "Health",
        "Public Sector",
        "Environment",
        "Cross Cutting Area",
    ],
    "Climate change and health vulnerability and adaptation assessment conducted": [
        "Health",
        "Environment",
        "Adaptation",
        "Public Sector",
    ],
    "Greenhouse gas emissions by sector": [
        "Environment",
        "Energy",
        "Agriculture",
        "Waste",
        "Industry",
        "Transport",
    ],
    "Emissions-weighted carbon price": [
        "Energy",
        "Industry",
        "Economy-wide",
        "Public Sector",
        "Finance",
    ],
    "Ocean Heat Content - Annual average": ["Environment", "Water", "Coastal zones"],
    "Tree Cover Loss by Dominant Driver": ["Environment", "LULUCF", "Agriculture"],
    "Concentrations of fine particulate matter (PM2.5)": [
        "Environment",
        "Health",
        "Energy",
        "Transport",
        "Industry",
    ],
    "Global Monthly Burned Area": [
        "Environment",
        "LULUCF",
        "Disaster Risk Management (Drm)",
    ],
    "Antarctic Ice Cores Revised 800KYr CO2 Data": [
        "Environment",
        "Cross Cutting Area",
    ],
    "Power sector emissions": ["Energy", "Environment", "Industry"],
    "Climate change attributable DALYs ('000)": [
        "Health",
        "Environment",
        "Cross Cutting Area",
    ],
    "Nitrous oxide emissions by sector": [
        "Agriculture",
        "Energy",
        "Waste",
        "Environment",
    ],
    "Emissions": [
        "Environment",
        "Energy",
        "Industry",
        "Transport",
        "Agriculture",
        "Waste",
    ],
    "Carbon dioxide emissions by sector": [
        "Environment",
        "Energy",
        "Industry",
        "Transport",
        "Agriculture",
        "Waste",
    ],
    "Climate change attributable deaths per 100'000 capita": [
        "Health",
        "Environment",
        "Cross Cutting Area",
    ],
    "OWID CO2 dataset": [
        "Environment",
        "Energy",
        "Industry",
        "Transport",
        "Agriculture",
        "Waste",
    ],
    "Climate Change Impacts - Annual": [
        "Environment",
        "Health",
        "Agriculture",
        "Water",
        "Adaptation",
        "Cross Cutting Area",
    ],
}

# Create a defaultdict to collect datasets by sector
sector_based_mapping = defaultdict(list)

# Populate sector_based_mapping by reversing sector_mapping
for dataset, sectors in sector_mapping.items():
    for sector in sectors:
        sector_based_mapping[sector].append(dataset)

# Convert defaultdict back to a regular dictionary (optional)
sector_based_mapping = dict(sector_based_mapping)
